routes:
  - path: /api/signup/request
    method: POST
    role: PUBLIC

  - path: /api/login/auth
    method: POST
    role: PUBLIC

  - path: /api/check-password/auth
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/change-password/auth
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/list/request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/logout/auth
    method: GET
    role: PUBLIC

  - path: /api/profile/user
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/edit/user
    method: PUT
    role: USER,ADMIN,SUPERADMIN

  - path: /api/add-admin/user
    method: POST
    role: SUPERADMIN

  - path: /api/approve/request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/multiple-approve/request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/reject/request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/view-details/request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/edit/branch
    method: PUT
    role: SUPERADMIN

  - path: /api/edit/admin
    method: PUT
    role: SUPERADMIN

  - path: /api/request/account-request
    method: POST
    role: USER

  - path: /api/pending/account-request
    method: GET
    role: USER

  - path: /api/list/account-request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/status-counts/request
    method: GET
    role: ADMIN,SUPERADMIN

  - path: /api/multiple-reject/request
    method: POST
    role: ADMIN,SUPERADMIN
 
  - path: /api/approve-account/admin
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/edit/account
    method: PUT
    role: ADMIN,SUPERADMIN
  
  - path: /api/add/branch
    method: POST
    role: SUPERADMIN

  - path: /api/withdraw/transaction
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/deposit/transaction
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/balance/account
    method: POST
    role: USER

  - path: /api/get-accounts/account
    method: POST
    role: USER

  - path: /api/total-balance/account
    method: POST
    role: USER

  - path: /api/transfer/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/statement/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/received-all/transaction
    method: POST
    role: USER

  - path: /api/received-account/transaction
    method: POST
    role: USER

  - path: /api/deposit-all/transaction
    method: POST
    role: USER

  - path: /api/deposit-account/transaction
    method: POST
    role: USER

  - path: /api/withdraw-all/transaction
    method: POST
    role: USER

  - path: /api/withdraw-account/transaction
    method: POST
    role: USER

  - path: /api/transfer-all/transaction
    method: POST
    role: USER

  - path: /api/transfer-account/transaction
    method: POST
    role: USER  

  - path: /api/recent-transactions/transaction
    method: POST
    role: USER

  - path: /api/income-account/transaction
    method: POST
    role: USER

  - path: /api/expense-account/transaction
    method: POST
    role: USER

  - path: /api/total-income/transaction
    method: POST
    role: USER

  - path: /api/total-expense/transaction
    method: POST
    role: USER

  - path: /api/get/branch
    method: POST
    role: SUPERADMIN

  - path: /api/get-all/branch
    method: POST
    role: SUPERADMIN

  - path: /api/get/admin
    method: POST
    role: SUPERADMIN

  - path: /api/get-all/admin
    method: POST
    role: SUPERADMIN

  - path: /api/get/account
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/get-all/account
    method: POST
    role: SUPERADMIN

  - path: /api/list-branch/account
    method: POST
    role: ADMIN,SUPERADMIN
 