routes:
  - path: /signup
    method: POST
    role: PUBLIC

  - path: /login
    method: POST
    role: PUBLIC

  - path: /logout
    method: GET
    role: PUBLIC

  - path: /user/dashboard
    method: GET
    role: USER

  - path: /admin/dashboard
    method: GET
    role: ADMIN

  - path: /admin/approve
    method: POST
    role: ADMIN

  - path: /admin/reject
    method: POST
    role: ADMIN

  - path: /admin/requests
    method: GET
    role: ADMIN

  - path: /superadmin/dashboard
    method: GET
    role: SUPER_ADMIN

  - path: /account/deposit
    method: POST
    role: ADMIN

  - path: /account/withdraw
    method: POST
    role: ADMIN

  - path: /account/transfer
    method: POST
    role: USER

  - path: /account/statement
    method: GET
    role: USER