routes:
  - path: /api/signup/request
    method: POST
    role: PUBLIC

  - path: /api/login/auth
    method: POST
    role: PUBLIC

  - path: /api/check-password/auth
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/change-password/auth
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/list/request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/logout/auth
    method: GET
    role: PUBLIC

  - path: /api/profile/user
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/get-profile/user
    method: POST
    role: USER,ADMIN,SUPERADMIN 

  - path: /api/edit/user
    method: PUT
    role: USER,ADMIN,SUPERADMIN

  - path: /api/add-admin/admin
    method: POST
    role: SUPERADMIN

  - path: /api/total-users/user
    method: GET
    role: ADMIN,SUPERADMIN

  - path: /api/total-accounts/account
    method: GET
    role: ADMIN,SUPERADMIN

  - path: /api/approve/request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/multiple-approve/request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/reject/request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/view-details/request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/edit/branch
    method: PUT
    role: SUPERADMIN

  - path: /api/edit/admin
    method: PUT
    role: SUPERADMIN

  - path: /api/request/account-request
    method: POST
    role: USER

  - path: /api/pending/account-request
    method: POST
    role: USER

  - path: /api/list/account-request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/view-details/account-request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/mutiple-reject/account-request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/reject/account-request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/multiple-approve/account-request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/status-counts/account-request
    method: GET
    role: ADMIN,SUPERADMIN

  - path: /api/status-counts/request
    method: GET
    role: ADMIN,SUPERADMIN

  - path: /api/multiple-reject/request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/multiple-reject/account-request
    method: POST
    role: ADMIN,SUPERADMIN
 
  - path: /api/approve-account/account-request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/edit/account
    method: PUT
    role: ADMIN,SUPERADMIN
  
  - path: /api/add/branch
    method: POST
    role: SUPERADMIN

  - path: /api/withdraw/transaction
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/deposit/transaction
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/balance/account
    method: POST
    role: USER

  - path: /api/get-accounts/account
    method: POST
    role: USER

  - path: /api/total-balance/account
    method: POST
    role: USER

  - path: /api/search-accounts/account
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/transfer/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/external-transfer/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/statement/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/received-all/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/received-account/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/deposit-all/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/deposit-account/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/withdraw-all/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/withdraw-account/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/transfer-all/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/transfer-account/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN 

  - path: /api/recent-transactions/transaction
    method: POST
    role: USER

  - path: /api/income-account/transaction
    method: POST
    role: USER

  - path: /api/expense-account/transaction
    method: POST
    role: USER

  - path: /api/total-income/transaction
    method: POST
    role: USER

  - path: /api/total-expense/transaction
    method: POST
    role: USER

  - path: /api/month-outgoing/transaction
    method: GET
    role: SUPERADMIN

  - path: /api/month-incoming/transaction
    method: GET
    role: SUPERADMIN

  - path: /api/total-type/transaction
    method: GET
    role: ADMIN,SUPERADMIN

  - path: /api/daily-counts/transaction
    method: POST
    role: ADMIN

  - path: /api/transaction-count/transaction
    method: GET
    role: SUPERADMIN

  - path: /api/get/branch
    method: POST
    role: SUPERADMIN

  - path: /api/get-all/branch
    method: POST
    role: SUPERADMIN

  - path: /api/total-branches/branch
    method: GET
    role: SUPERADMIN

  - path: /api/without-admin/branch
    method: GET
    role: SUPERADMIN

  - path: /api/branch-funds/branch
    method: GET
    role: SUPERADMIN

  - path: /api/all-branch/branch
    method: GET
    role: USER,ADMIN,SUPERADMIN,PUBLIC

  - path: /api/get/admin
    method: POST
    role: SUPERADMIN

  - path: /api/total-admins/admin
    method: GET
    role: SUPERADMIN

  - path: /api/get-all/admin
    method: POST
    role: SUPERADMIN

  - path: /api/get/account
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /api/get-all/account
    method: POST
    role: SUPERADMIN,ADMIN

  - path: /api/list-branch/account
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /api/account-summary/transaction
    method: POST
    role: ADMIN
 