routes:
  - path: /signup
    method: POST
    role: PUBLIC

  - path: /login
    method: POST
    role: PUBLIC

  - path: /logout
    method: GET
    role: PUBLIC

  - path: /profile
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /admin/dashboard
    method: GET
    role: ADMIN

  - path: /admin/approve
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /admin/reject
    method: POST
    role: ADMIN

  - path: /admin/requests
    method: POST
    role: ADMIN

  - path: /account/deposit
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /account/withdraw
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /account/transfer
    method: POST
    role: USER

  - path: /account/statement
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /account/balance
    method: POST
    role: USER
 
  - path: /superadmin/add/employee
    method: POST
    role: SUPERADMIN

  - path: /superadmin/add/branch
    method: POST
    role: SUPERADMIN

  - path: /edit/profile
    method: PUT
    role: USER,ADMIN,SUPERADMIN

  - path: /edit/branch
    method: PUT
    role: SUPERADMIN

  - path: /edit/employee
    method: PUT
    role: SUPERADMIN