routes:
  - path: /signup/request
    method: POST
    role: PUBLIC

  - path: /login/user
    method: POST
    role: PUBLIC

  - path: /list/request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /logout
    method: GET
    role: PUBLIC

  - path: /profile/user
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /edit/user
    method: PUT
    role: USER,ADMIN,SUPERADMIN

  - path: /add-admin/user
    method: POST
    role: SUPERADMIN

  - path: /approve/request
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /edit/branch
    method: PUT
    role: SUPERADMIN

  - path: /edit/admin
    method: PUT
    role: SUPERADMIN

  - path: /request/account-request
    method: POST
    role: USER,ADMIN,SUPERADMIN
 
  - path: /approve-account/admin
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /edit/account
    method: PUT
    role: ADMIN,SUPERADMIN
  
  - path: /add/branch
    method: POST
    role: SUPERADMIN

  - path: /withdraw/transaction
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /deposit/transaction
    method: POST
    role: ADMIN,SUPERADMIN

  - path: /balance/account
    method: POST
    role: USER

  - path: /transfer/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN

  - path: /statement/transaction
    method: POST
    role: USER,ADMIN,SUPERADMIN